import type { PersonalCategorySeed } from "./types";

export const DEFAULT_PERSONAL_CATEGORIES: PersonalCategorySeed[] = [
  {
    name: "Salario",
    type: "income",
    icon: "briefcase",
    colorToken: "green",
    keywords: ["salario", "sueldo", "nomina", "payroll", "salary"],
  },
  {
    name: "Independiente",
    type: "income",
    icon: "sparkles",
    colorToken: "blue",
    keywords: ["freelance", "independiente", "servicio", "honorarios", "proyecto"],
  },
  {
    name: "Ventas",
    type: "income",
    icon: "briefcase",
    colorToken: "green",
    keywords: ["venta", "ventas", "pedido", "cliente pago", "comision"],
  },
  {
    name: "Inversiones",
    type: "income",
    icon: "chart",
    colorToken: "blue",
    keywords: ["inversion", "rendimiento", "dividendo", "intereses", "rentabilidad"],
  },
  {
    name: "Arriendo",
    type: "income",
    icon: "home",
    colorToken: "sand",
    keywords: ["arriendo recibido", "renta recibida", "alquiler recibido"],
  },
  {
    name: "Regalos",
    type: "income",
    icon: "sparkles",
    colorToken: "pink",
    keywords: ["regalo", "detalle", "obsequio"],
  },
  {
    name: "Otros ingresos",
    type: "income",
    icon: "circle",
    colorToken: "yellow",
    keywords: ["ingreso", "extra", "transferencia recibida", "bonus", "bono"],
  },
  {
    name: "Alimentacion",
    type: "expense",
    icon: "utensils",
    colorToken: "sand",
    keywords: ["almuerzo", "comida", "restaurante", "cafe", "coffee", "desayuno", "cena", "mercado", "d1", "ara", "exito", "super"],
  },
  {
    name: "Transporte",
    type: "expense",
    icon: "car",
    colorToken: "blue",
    keywords: ["gasolina", "uber", "taxi", "bus", "metro", "transporte", "parking", "parqueadero"],
  },
  {
    name: "Vivienda",
    type: "expense",
    icon: "home",
    colorToken: "green",
    keywords: ["arriendo", "renta", "hipoteca", "vivienda", "hogar", "administracion"],
  },
  {
    name: "Servicios",
    type: "expense",
    icon: "home",
    colorToken: "blue",
    keywords: ["servicios", "luz", "agua", "gas", "internet", "celular", "telefono", "energia"],
  },
  {
    name: "Suscripciones",
    type: "expense",
    icon: "repeat",
    colorToken: "pink",
    keywords: ["netflix", "spotify", "prime", "icloud", "suscripcion", "subscription"],
  },
  {
    name: "Salud",
    type: "expense",
    icon: "heart",
    colorToken: "pink",
    keywords: ["salud", "medico", "farmacia", "doctor", "medicina"],
  },
  {
    name: "Educacion",
    type: "expense",
    icon: "file",
    colorToken: "blue",
    keywords: ["colegio", "universidad", "curso", "educacion", "matricula", "libro"],
  },
  {
    name: "Entretenimiento",
    type: "expense",
    icon: "sparkles",
    colorToken: "pink",
    keywords: ["cine", "bar", "salida", "juego", "entretenimiento", "concierto"],
  },
  {
    name: "Compras",
    type: "expense",
    icon: "credit",
    colorToken: "sand",
    keywords: ["compra", "ropa", "zapatos", "tienda", "amazon", "mercadolibre"],
  },
  {
    name: "Deudas",
    type: "expense",
    icon: "credit",
    colorToken: "pink",
    keywords: ["deuda", "cuota", "pago credito", "tarjeta", "prestamo"],
  },
  {
    name: "Familia",
    type: "expense",
    icon: "users",
    colorToken: "green",
    keywords: ["familia", "hijo", "hija", "papas", "mama", "papa"],
  },
  {
    name: "Viajes",
    type: "expense",
    icon: "car",
    colorToken: "blue",
    keywords: ["viaje", "hotel", "vuelo", "peaje", "vacaciones"],
  },
  {
    name: "Mascotas",
    type: "expense",
    icon: "heart",
    colorToken: "green",
    keywords: ["mascota", "perro", "gato", "veterinario", "concentrado"],
  },
  {
    name: "Impuestos",
    type: "expense",
    icon: "file",
    colorToken: "yellow",
    keywords: ["impuesto", "renta", "predial", "vehiculo", "dian"],
  },
  {
    name: "Otros",
    type: "expense",
    icon: "circle",
    colorToken: "yellow",
    keywords: ["otro", "varios", "misc"],
  },
];

export function findCategorySeedByName(name: string) {
  const normalized = name.trim().toLowerCase();
  return DEFAULT_PERSONAL_CATEGORIES.find((category) => category.name.toLowerCase() === normalized) ?? null;
}
